; sa se tipareasca lista nodurilor de pe nivelul k dintr-un arbore de tipul (1)
; tipul (1) = (A 2 B 1 C 0 D 2 E 1 F 0)
; pentru K=2 si arborele (A 2 B 2 H 0 C 0 D 2 E 1 F 0) se va tipari (H C E)

(defun nivelk (l l2Radacina nv nm nivel k l2Ant nrMuchii dif col)
  (cond 
    ((null l) col)
    ((= nv (+ nm 1)) (nivelk l l2Radacina 0 0 0 k l2Radacina 0 0 col))
    ((and (not (= l2Ant 0)) (not (= (cadr l) 0)))
     (progn
    ;    (print 'cazul_l2Ant_dif_0_si_l2_dif_0)
    ;    (print (list 'current-node (car l)))
    ;    (print (+ nivel 1))
       (let ((new-col col))
         (when (= (+ nivel 1) k)
           (setq new-col (cons (car l) new-col))
           (print (list 'new-col new-col))
         )  
         (nivelk (cddr l) l2Radacina (+ nv 1) (+ nm (cadr l)) (+ nivel 1) k (cadr l) (cadr l) (+ dif 1) new-col)
       )
     )
    )
    ((and (not (= l2Ant 0)) (= (cadr l) 0))
     (progn
    ;    (print 'cazul_l2Ant_dif_0_si_l2_0)
    ;    (print (list 'current-node (car l)))  
    ;    (print (+ nivel 1))
       (let ((new-col col))
         (when (= (+ nivel 1) k)
           (setq new-col (cons (car l) new-col))
           (print (list 'new-col new-col))
         )
         (nivelk (cddr l) l2Radacina (+ nv 1) (+ nm (cadr l)) (+ nivel 1) k (cadr l) (- l2Ant 1) dif new-col)
       )
     )
    )
    ((and (= l2Ant 0) (not (= nrMuchii 0)))
     (progn
    ;    (print 'cazul_l2Ant_0_si_nrMuchii_dif_0)
    ;    (print (list 'current-node (car l))) 
    ;    (print nivel)
       (let ((new-col col))
         (when (= nivel k)
           (setq new-col (cons (car l) new-col))
           (print (list 'new-col new-col))
         ) 
         (nivelk (cddr l) l2Radacina (+ nv 1) (+ nm (cadr l)) nivel k (cadr l) (- nrMuchii 1) dif new-col)
       )
     )
    )
    ((and (= l2Ant 0) (= nrMuchii 0))
     (progn
    ;    (print 'cazul_l2Ant_0_si_nrMuchii_0)
    ;    (print (list 'current-node (car l))) 
    ;    (print (- nivel (- dif 1)))
    ;    (print dif)
       (let ((new-col col))
         (when (= (- nivel (- dif 1)) k)
           (setq new-col (cons (car l) new-col))
           (print (list 'new-col new-col))
         )  
         (nivelk (cddr l) l2Radacina (+ nv 1) (+ nm (cadr l)) (- nivel (- dif 1)) k (cadr l) (cadr l) (- dif 1) new-col)
       )
     )
    )
  )
)

(defun main (k l)
  (cond
    ((= k 0) (print (list (car l))))
    (t (print (reverse (nivelk (cddr l) (cadr l) 0 0 0 k (cadr l) 0 0 nil))))
  )
)

(main 3 '(A 2 B 2 D 1 E 1 K 0 F 2 G 0 H 0 C 1 I 1 J 0))
(main 2 '(A 2 B 2 H 0 C 0 D 2 E 1 F 0))
(main 0 '(A 2 B 0 C 0))